name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Lane4 Jardis Factory - Run Build, QA Tools and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: |
          mkdir -p $DOCKER_CONFIG
          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Pull Docker Image
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: docker pull lane4jardis/phpcli:latest

      - name: Install dependencies
        run: make install

      - name: Check Code Standards with PHPCS
        run: make phpcs

      - name: Run PHPUnit Tests with Coverage
        run: make phpunit-coverage

      - name: Run PHPStan (Static Analysis)
        run: make phpstan

      - name: Tear Down Docker Environment
        if: always()
        run: make remove

      - name: Logout from Docker Hub
        if: always()
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: docker logout
